accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path("redirect/", views.login_redirect_view, name="redirect"),
    path("account-profile/", views.BuyerProfileView.as_view(), name="buyer_profile"),
    path("account-profile-details-with-foreignkey-relationship/account/detail/",views.account_view),
    
    path("search-engine/", views.SearchEngineView.as_view(), name="search_engine")
]

adminb2b/urls.py
from django.urls import path
from . import views
app_name="adminb2b"
urlpatterns = [
    path("", views.Adminb2bView.as_view(), name="admin_dahboard"),
    path("seller-list/", views.AdminSellerListView.as_view(), name="admin_seller_list"),
    path("seller/<int:pk>/", views.AdminSellerDetailView.as_view(), name="admin_seller_detail"),
    path("buyer-list/", views.AdminBuyerListView.as_view(), name="admin_buyer_list"),
    
    path("enquiry-list/", views.EnquiryListView.as_view(), name="enquiry_list"),
    path("enquiry-detail/<int:pk>/", views.EnquiryDetailView.as_view(), name="enquiry_detail"),

    path("enquiry-approve/<int:pk>/", views.EnquiryApproveView.as_view(), name="enquiry_approve"),
    path("enquiry-unapprove/<int:pk>/", views.EnquiryUnApproveView.as_view(), name="enquiry_unapprove"),

    path("seller-address-list/", views.SellerAddressListView.as_view(), name="seller_address_list"),
    path("seller-address-approve/<int:pk>/", views.AddressApproveView.as_view(), name="seller_address_approve"),
    path("seller-address-unapprove/<int:pk>/", views.AddressUnApproveView.as_view(), name="seller_address_unapprove"),
    path("seller-address-admin-account-approve-unapprove-notification/admin-user-account-view/", views.admin_account_view),

    path("admin-user-list/", views.AdminUserListView.as_view(), name="admin_user_list"),
    path("admin-user-activate/<int:pk>/", views.UserActivateView.as_view(), name="admin_user_activate"),
    path("admin-user-deactivate/<int:pk>/", views.UserDeactivateveView.as_view(), name="admin_user_deactivate"),

]

b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from product.models import Order
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),
    path('editor-choice/', TemplateView.as_view(template_name="company/choice.html"), name="choice"),
    path('category-leader/', TemplateView.as_view(template_name="company/leader.html"), name="leader"),
    path('fund-your-order-center/', TemplateView.as_view(template_name="company/order-center.html"), name="center"),
    path('customer-with-viswas-certification/', TemplateView.as_view(template_name="company/certification.html"), name="certification"),

    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('adminb2b/', include('adminb2b.urls', namespace="adminb2b")),
    path('subscription/', include('subscription.urls', namespace="subscription")),

    path('', include("product.urls", namespace="product")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),

    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),


    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryListView.as_view(), name="seller_my_enquiry_list"),
    path('seller/my-enquiry/<int:pk>/',views.SellerMyEnquiryDetailView.as_view(), name="seller_my_enquiry_detail"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('<str:slug>/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),
    path('seller/banner-logo/<str:slug>/',views.SellerBannerLogoView.as_view(), name="seller_banner_logo"),
    path('seller/color/<str:slug>/',views.ColorView.as_view(), name="seller_color"),

    path('seller/create-product/',views.ProductCreateView.as_view(), name="create_product"),
    path('seller/update-product/<int:pk>/',views.ProductUpdateView.as_view(), name="update_product"),
    path('seller/create-bulk-product/',views.BulkProductUploadView.as_view(), name="create_bulk_product"),

    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    # path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),
    path('buyer-share/',views.SellerShareView.as_view(), name="seller_share"),
    path('buyer-seller-dashboard-product-variant-upload-record-list/',views.dashboard_account_view),
    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),

    path('share-detail-admin/',views.ShareDetailAdmin.as_view(), name="share_detail_admin"),

    path('seller-order-list/', views.SellerOrderListView.as_view(), name='seller_order_list'),
    path('seller-order-detail/<int:pk>/', views.SellerOrderDetailView.as_view(), name='seller_order_detail'),
    path('generate-pdf/<int:pk>/', views.GeneratePdf.as_view(), name='generate_pdf'),

    path('seller-order-confirmed/<int:pk>/', views.SellerOrderConfirmedView.as_view(), name='seller_order_confirmed'),
    path('seller-order-processing/<int:pk>/', views.SellerOrderProcessingView.as_view(), name='seller_order_processing'),
    path('seller-quality-check/<int:pk>/', views.SellerQualityCheckView.as_view(), name='seller_quality_check'),
    path('seller-product-disparch/<int:pk>/', views.SellerProductDispatchView.as_view(), name='seller_product_dispatch'),
    path('seller-product-selivered/<int:pk>/', views.SellerProducrDeliveredView.as_view(), name='seller_product_delivered'),



    path('add-to-cart/<str:slug>/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<str:slug>/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove-product-from-cart/<str:slug>/<int:pk>/', views.remove_single_product_from_cart, name='remove_single_product_from_cart'),
    path('<str:slug>/cart/', views.CartView.as_view(), name='cart'),


    path('generate-otp/', views.GenerateOtpView.as_view(), name='generate_otp'),
    path('verify-otp/', views.VerifyOtpView.as_view(), name='verify_otp'),

    path('buyer-enquiry/', views.BuyerEnquiryView.as_view(), name='buyer_enquiry'),

    path('credit-terms/', views.credit_terms_view, name='credit_terms'),
    
    path('seller-paid-service/', views.seller_paid_service, name='seller_paid_service'),

]

product/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name="product"

urlpatterns = [
    path("handlerequest/", views.handlerequest, name="HandleRequest"),
    path("back/", views.back, name="back"),
    path("preview/<str:slug>/",views.SitePreviewView.as_view(), name="preview"),


    path("",views.HomeView, name="home_list"),
    path("category/",views.category, name="category"),
    path("<str:slug>/",views.WebsiteHomeList.as_view(), name="website_home_list"),

    path("product/checkout/",views.CheckoutView.as_view(), name="product_checkout"),
    path("product/order-track/<int:pk>/",views.ProductTrackView.as_view(), name="product_order_track"),

    path("product/add-to-cart/<str:slug>/<int:pk>/",views.AddToCart.as_view(), name="add_to_cart"),
    
    path("product/cart-summary/",views.CartView.as_view(), name="cart_summary"),

    path("product/remove-from-cart/<int:pk>/",views.RemoveFromCartView.as_view(), name="remove_from_cart"),
    path("product/remove-single-item-from-cart/<int:pk>/",views.RemoveSingleItemFromCartView.as_view(), name="remove_single_item_from_cart"),
    path("product/add-single-item-to-cart/<int:pk>/",views.AddSingleItemToCartView.as_view(), name="add_single_item_to_cart"),
    ####compare route########

    path("product/compare-product-list/",views.CompareView.as_view(), name="compare_view"),

    path("product/remove-compare-product/<int:pk>/",views.RemoveFromCompareView.as_view(), name="remove_from_compare"),
    # path("product/remove-single-item-compare-product/<int:pk>/",views.RemoveSingleItemFromCompareView.as_view(), name="remove_single_item_from_compare"),
    path("product/add-single-item-to-compare-product/<int:pk>/",views.AddSingleItemToCompareView.as_view(), name="add_single_item_to_compare"),

    ]

templates/template_blocks/footers.html
{% load static %}
<style>
  @media only screen and (max-width: 400px){
      .teamdilip{
          display: flex;
          flex-direction: column;;
          justify-content:center;
          align-items:center
      }
  }

footer ul li a {
    color: #c3bfbf;
}  
</style>
 <div class="newstetter text-center pt-4 pb-4 mt-3">
      <h2 class="text-uppercase"><span>subscribe</span> to our newsletter</h2>
      <small>The best B2B news for manufacturers and traders</small>
      <form action="{% url 'subscription:subscription_newsletter' %}" method="post">
        {% csrf_token %}
      <div class="input-group  col-sm-12 col-lg-6 mx-auto mt-4">
        <input type="email" id="id_email" class="form-control" name="email" placeholder="Enter your email" aria-label="Enter your email" aria-describedby="subscribe">
        <div class="input-group-append">
          <span class="input-group-text" id="subscribe"><input type="submit" style="background:none" value="Subscribe"></span>
        </div>
      </div>
    </form>
    </div>

    <footer class="pt-5 pb-5 ">
      <div class="container">
        <div class="row">
          <div class="col-6 col-sm-6 col-lg-2 mx-auto mb-2">
            <a href="{% url 'product:home_list' %}">
              <img id="img_footer"  src="{% static 'images/logo-white.png' %}" alt="" style="max-width: 146px;">
            </a>
          </div>
          <div class="col-12 col-sm-6 col-lg-2">
            <ul class="">
              <li class="head">WHO WE ARE</li>
              <li><a href="{% url 'about_us' %}">About Ramagyamart</a></li>
              <li><a href="#">Vision | Mission</a></li>
              <li><a href="{% url 'media_center' %}">News About Us</a></li>
              <li><a href="{% url 'about_management' %}">Management Team</a></li>
              <li><a href="{% url 'about_work_with_us' %}">Work With Us</a></li>
              <!--<li><a href="{% url 'about_contact_us' %}">Contact Us</a></li>-->
            </ul>
          </div>
          <div class="col-12 col-sm-6 col-lg-3">
              <ul class="">
              <li class="head">OUR SERVICES</li>
              <li><a href="{% url 'subscription:paid_service' %}">Ramagya Vishwas Certification</a></li>
              <li><a href="{% url 'subscription:paid_service' %}">Enroll For Editors Pick</a></li>
              <li><a href="{% url 'subscription:paid_service' %}">Category Leaders Certification</a></li>
              <li><a href="{% url 'subscription:paid_service' %}">White Labelling Solutions</a></li>
              {% comment %}<li><a href="{% url 'dashboard:seller_company' %}">E-Shoppe Development</a></li>{% endcomment %}
              <!--<li><a href="{% url 'media_center' %}">Media Center</a></li>-->
              <li><a href="{% url 'advertise' %}">Advertise Your Brand</a></li>
              <!-- <li><a href="#">Transact To Trade</a></li> -->
            </ul>
            
          </div>
          <div class="col-12 col-sm-6 col-lg-3">
            <ul class="">
              <li class="head">CUSTOMER SUPPORT</li>
              <li><a href="{% url 'help_center' %}">Help Center</a></li>
              <li><a href="{% url 'privacy_policy' %}">privacy policy</a></li>
              <li><a href="{% url 'trading_policy' %}">Trading policy</a></li>
              <li><a href="{% url 'term_condition' %}">terms & conditions</a></li>
              <!-- <li><a href="{% url 'edit_profile' %}">edit Profile</a></li> -->
            </ul>
          </div>
          <div class="col-12 col-sm-6 col-lg-2">
            <ul class="text-center">
              <li class="head">Follow us</li>
              <li>
                <a href="https://www.facebook.com/Ramagyamart/"><img src="{% static 'images/fb.png' %}" alt="facebook"></a> | 
                <a href="https://www.instagram.com/ramagyamart/"><img src="{% static 'images/insta.png' %}" alt="instagram"></a> | 
                <a href="https://www.linkedin.com/company/ramagyamart/"><img src="{% static 'images/linkedin.png' %}" alt="linkedin"></a>
                <a href="https://www.youtube.com/channel/UCfL0UX82V-JgeUzeaCpRUYQ"><img src="{% static 'images/youtube.png' %}" alt="youtube"></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <div class="copyright text-center pt-3 pb-3">
      <p class="mb-3">&#169; 2021 Ramagya Mart</p>
      <img src="{% static 'images/footerSub.png' %}" alt="">
    </div>

templates/template_blocks/navbar.html
{% load static %}


{% load cart_template_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% include 'template_blocks/head_css.html' %}
{% include 'template_blocks/javascript.html' %}

<style>

 * {
  box-sizing: border-box;
}

#mobilecarousel{
  display:none;
}

/*when hovering an item:*/
.autocomplete-items div:hover {
  background-color: #e9e9e9;
}

/*when navigating through the items using the arrow keys:*/

.carousel_mobile,.mobile_search ,.mobile_button,.carouselexample,.first,.mobile_feature{
    display: none;
  }
.carousel-indicators{
    margin-bottom:4050px;
  }

/*responsive*/
@media (min-width:800px){
    .certi{
        width:190px;
    }
    .dash{
        font-size: 35px;
    margin-right: 2%;
    color:white;
    }
    .udhar{
    margin-top:2%;
    }
}

@media screen and (max-width:640px) and (min-width:300px){

.navbar{
  width: 100%;
   margin-left: 0px;
}
}

@media screen and (max-width:580px) and (min-width:300px){
    .dash{
        display:none;
    }
   .navbar,.fluid,.container{
    width:100%;
    margin-left: 0px;

  }
  .image{
    width:90px;

  }
  .ml-5, .mx-5 {
     margin-left: 0rem !important;
     font-size: 17px;
   }
.navbar-toggler, {
    width:40px;

  }
  .navbar-toggler-icon{
     margin-right:-1px;
  }
}
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img class="image" src="{% static 'images/logo-white.png' %}" alt="" style="max-width: 129px;">
      <span >| <i>Desh Ka Vyapar</i></span>
    </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar"  aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav m-auto w-33">
      {% if  request.user.account.business_type == "Seller" %}
         <li class="nav-item">
              <img src="{% static 'images/certii.png' %}" style="height:55px">
         </li>
        <li class="nav-item certi">
          <a class="nav-link" href="{% url 'subscription:paid_service' %}">Apply For Ramagya <br> Vishwas Certification</a>
        </li>
         <li class="nav-item dash" >
          <a style="color:white;">|</a>
        </li>
        {% else %}
        {% endif %}
        
        <li class="nav-item udhar">
              <img src="{% static 'images/30day.png' %}" class="" style="height:35px;">
        </li>
        <li class="nav-item">
          <a class="nav-link"href="{% url 'subscription:paid_service' %}">Ramagya <br> Udhar</a>
        </li>
        
        <li class="nav-item dash" >
          <a>|</a>
        </li>
        
        <li class="nav-item udhar">
              <img src="{% static 'images/loginn.png' %}" class="" style="height:35px;">
        </li>
        
        {% if not request.user.is_authenticated%}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            User Login
          </a>
          <div class="dropdown-menu">
            {% if request.user.account.business_type == "Seller" %}
            <a class="dropdown-item" href="{% url 'dashboard:seller_contact_profile' %}">Seller</a>
            {% elif request.user.account.business_type == "Buyer" %}
            <a class="dropdown-item" href="{% url 'accounts:buyer_profile' %}">Buyer</a>
            {% endif %}
            
            {% if not request.user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'dashboard:seller_contact_profile' %}">Seller</a>
              <a class="dropdown-item" href="{% url 'accounts:buyer_profile' %}">Buyer</a>
            {% endif %}
          </div>
        </li>
        {% else %}
        <li class="nav-item">
            {% if request.user.account.business_type == "Seller" %}
            <a class="nav-link" href="{% url 'dashboard:seller_contact_profile' %}">Seller</a>
            {% elif request.user.account.business_type == "Buyer" %}
            <a class="nav-link" href="{% url 'accounts:buyer_profile' %}">Buyer</a>
            {% endif %}
         
        </li>
        {% endif %}
        
        <li class="nav-item dash" >
          <a>|</a>
        </li>
        
        <li class="nav-item udhar">
              <img src="{% static 'images/helpp.png' %}" class="" style="height:35px;">
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'help' %}">Help</a>
        </li>
        
        {% comment %} <!--{% if request.user.account.business_type == "Seller" %}-->
        <!--<li class="nav-item">-->
        <!--  <a class="nav-link" href="{% url 'dashboard:seller_contact_profile' %}">Seller</a>-->
        <!--</li>-->
        <!--{% elif request.user.account.business_type == "Buyer" %}-->
        <!--<li class="nav-item">-->
        <!--  <a class="nav-link" href="{% url 'accounts:buyer_profile' %}">Buyer</a>-->
        <!--</li>-->
        <!--{% endif %}-->

        <!--{% if not request.user.is_authenticated %}-->
        <!--<li class="nav-item">-->
        <!--  <a class="nav-link" href="{% url 'dashboard:seller_contact_profile' %}">Seller</a>-->
        <!--</li>-->
        <!--<li class="nav-item">-->
        <!--  <a class="nav-link" href="{% url 'accounts:buyer_profile' %}">Buyer</a>-->
        <!--</li>-->
        <!--{% endif %}-->
    <!--{% if request.user.is_authenticated %}-->
    <!--    {% if not request.user.account.business_type == "Seller" and not request.user.is_superuser %}-->
    <!--    <li class="nav-item">-->
    <!--      <a class="nav-link cart" href="{% url 'dashboard:cart' slug='seller' %}">-->
    <!--        <img src="{% static 'images/cart.png' %}" alt="">-->
    <!--        <span>My Cart</span>-->
    <!--        {% endif %}-->
    <!--        {% if request.user|cart_product_count %}<span class="badge red z-depth-1 mr-1"> <span class="badge rounded-pill bg-danger px-2">{{ request.user|cart_product_count }} </span></span>{% endif %}-->
    <!--      </a>-->
    <!--    </li>-->
    <!--    <li class="nav-item login">-->
    <!--      <a class="nav-link" href="{% url 'account_logout' %}">-->
    <!--        <img src="{% static 'images/login.png' %}" alt="">-->
    <!--        <span>Log Out</span>-->
    <!--      </a>-->
    <!--    </li>-->
    <!--    {% else %}-->
    <!--    <li class="nav-item login">-->
    <!--      <a class="nav-link" href="{% url 'account_login' %}">-->
    <!--        <img src="{% static 'images/login.png' %}" alt="">-->
    <!--        <span>Log in New User</span>-->
    <!--      </a>-->
    <!--    </li>-->

    <!--    {% endif %}--> {% endcomment %}

        <li class="nav-item dash" >
          <a>|</a>
        </li>
        <li class="nav-item udhar">
              <img src="{% static 'images/ad.png' %}" style="height:35px;">
        </li>
        <li class="nav-item">
          <a class="nav-link pr-0" href="{% url 'subscription:paid_service' %}">
            Advertise <br>with us
          </a>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item login">
          <a class="nav-link" href="{% url 'adminb2b:enquiry_list' %}">
            Admin
          </a>
        </li>
        {% endif %}
        {% if request.user.is_authenticated %}
        <li class="nav-item dash" >
          <a>|</a>
        </li>
        <li class="nav-item udhar">
        <img src="{% static 'images/login.png' %}" alt="">
        </li>
        <li>
          <a class="nav-link" href="{% url 'account_logout' %}">
            <span>Log Out</span>
          </a>
        </li>
      {% else %}
      {% endif %}
      </ul>
     
    </div>
  </div>
</nav>
<script>
$('.navbar-toggler').click(function(){
if(document.getElementById("collapsibleNavbar").classList.contains("show")){
  $('#collapsibleNavbar').removeClass("show")
   $(".navbar-toggler").removeAttr('data-toggle','collapse');
}
else
{
  $(".navbar-toggler").attr('data-toggle','collapse');
}
})

</script>