accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path("redirect/", views.login_redirect_view, name="redirect"),
    path("account-profile/", views.BuyerProfileView.as_view(), name="buyer_profile"),
    path("account-profile-details-with-foreignkey-relationship/account/detail/",views.account_view),
    
    path("search-engine/", views.SearchEngineView.as_view(), name="search_engine")
]

b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from product.models import Order
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),
    path('editor-choice/', TemplateView.as_view(template_name="company/choice.html"), name="choice"),
    path('category-leader/', TemplateView.as_view(template_name="company/leader.html"), name="leader"),
    path('fund-your-order-center/', TemplateView.as_view(template_name="company/order-center.html"), name="center"),
    path('customer-with-viswas-certification/', TemplateView.as_view(template_name="company/certification.html"), name="certification"),

    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('adminb2b/', include('adminb2b.urls', namespace="adminb2b")),
    path('subscription/', include('subscription.urls', namespace="subscription")),

    path('', include("product.urls", namespace="product")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),

    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),


    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryListView.as_view(), name="seller_my_enquiry_list"),
    path('seller/my-enquiry/<int:pk>/',views.SellerMyEnquiryDetailView.as_view(), name="seller_my_enquiry_detail"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('<str:slug>/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),
    path('seller/banner-logo/<str:slug>/',views.SellerBannerLogoView.as_view(), name="seller_banner_logo"),
    path('seller/color/<str:slug>/',views.ColorView.as_view(), name="seller_color"),

    path('seller/create-product/',views.ProductCreateView.as_view(), name="create_product"),
    path('seller/update-product/<int:pk>/',views.ProductUpdateView.as_view(), name="update_product"),
    path('seller/create-bulk-product/',views.BulkProductUploadView.as_view(), name="create_bulk_product"),

    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    # path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),
    path('buyer-share/',views.SellerShareView.as_view(), name="seller_share"),
    path('buyer-seller-dashboard-product-variant-upload-record-list/',views.dashboard_account_view),
    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),

    path('share-detail-admin/',views.ShareDetailAdmin.as_view(), name="share_detail_admin"),

    path('seller-order-list/', views.SellerOrderListView.as_view(), name='seller_order_list'),
    path('seller-order-detail/<int:pk>/', views.SellerOrderDetailView.as_view(), name='seller_order_detail'),
    path('generate-pdf/<int:pk>/', views.GeneratePdf.as_view(), name='generate_pdf'),

    path('seller-order-confirmed/<int:pk>/', views.SellerOrderConfirmedView.as_view(), name='seller_order_confirmed'),
    path('seller-order-processing/<int:pk>/', views.SellerOrderProcessingView.as_view(), name='seller_order_processing'),
    path('seller-quality-check/<int:pk>/', views.SellerQualityCheckView.as_view(), name='seller_quality_check'),
    path('seller-product-disparch/<int:pk>/', views.SellerProductDispatchView.as_view(), name='seller_product_dispatch'),
    path('seller-product-selivered/<int:pk>/', views.SellerProducrDeliveredView.as_view(), name='seller_product_delivered'),



    path('add-to-cart/<str:slug>/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<str:slug>/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove-product-from-cart/<str:slug>/<int:pk>/', views.remove_single_product_from_cart, name='remove_single_product_from_cart'),
    path('<str:slug>/cart/', views.CartView.as_view(), name='cart'),


    path('generate-otp/', views.GenerateOtpView.as_view(), name='generate_otp'),
    path('verify-otp/', views.VerifyOtpView.as_view(), name='verify_otp'),

    path('buyer-enquiry/', views.BuyerEnquiryView.as_view(), name='buyer_enquiry'),

    path('credit-terms/', views.credit_terms_view, name='credit_terms'),
    
    path('seller-paid-service/', views.seller_paid_service, name='seller_paid_service'),

]

dashboard/models.py
from django.db import models
from accounts.models import Account
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from embed_video.fields import EmbedVideoField


class SellerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    promoter_first_name = models.CharField(max_length=50)
    promoter_last_name = models.CharField(max_length=50)
    designation = models.CharField(max_length=50)
    address_building = models.CharField(max_length=100)
    address_area = models.CharField(max_length=100)
    landmark = models.CharField(max_length=50)
    locality = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    gstin = models.CharField(max_length=50, blank=True, null=True, default=None)
    company_website = models.CharField(max_length=50)
    alternative_mobile = models.CharField(max_length=50)
    alternative_email = models.EmailField(max_length=50)
    landline_no = models.CharField(max_length=50)
    alternative_landline_no = models.CharField(max_length=50)
    about_me = models.TextField()
    approve = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username



def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 2.0
    if filesize > megabyte_limit*1024*1024:
        raise ValidationError("Max file size is %sMB" % str(megabyte_limit))


class BusinessProfile(models.Model):
    CATEGORY = (
			('Seller', 'Seller'),
			('Manufacturer', 'Manufacturer'),
			) 
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='businessprofile')
    year_of_establishment = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=200, blank=True, null=True)
    category = models.CharField(max_length=200, blank=True, null=True, choices=CATEGORY)
    annual_turnover = models.CharField(max_length=200, blank=True, null=True)
    company_card_front_view = models.ImageField(upload_to='company_card_images', null=True, blank=True)
    company_card_back_view = models.ImageField(upload_to='company_card_images', null=True, blank=True)
    
    def __str__(self):
        return self.user.username

      
class SellerStatutory(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gst_no = models.CharField(max_length=50, null=True, blank=True)
    pan_no = models.CharField(max_length=50, null=True)
    tan_no = models.CharField(max_length=50, null=True)
    cin_no = models.CharField(max_length=100, null=True)
    dgft_ie_code = models.CharField(max_length=100, null=True)
    company_registration_no = models.URLField(max_length=50, null=True)

    def __str__(self):
        return self.user.username
    

class SellerBank(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bank_name = models.CharField(max_length=50)
    account_no = models.CharField(max_length=50)
    bank_account_name = models.CharField(max_length=50)
    ifsc_code = models.CharField(max_length=50)
    account_type = models.CharField(max_length=50)
    alternative_bank_name = models.CharField(max_length=50, blank=True, null=True)
    alternative_account_no = models.CharField(max_length=50, blank=True, null=True)
    alternative_bank_account_name = models.CharField(max_length=50, blank=True, null=True)
    alternative_bank_ifsc_code = models.CharField(max_length=50, blank=True, null=True)
    alternative_bank_account_type = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.user.username



from django.db.models.signals import post_save
def businessprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = BusinessProfile.objects.create(user=instance)


post_save.connect(businessprofile_receiver, sender=User)

class SellerCompany(models.Model):
    CATEGORY = (
			('Proprietorship', 'Proprietorship'),
			('Partnership', 'Partnership'),
            ('LLP', 'LLP'),
            ('OPC', 'OPC'),
            ('Private Ltd', 'Private Ltd'),
            ('Limited', 'Limited'),
			) 
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='sellercompany')
    about_seller = models.TextField(blank=True, null=True)
    no_of_employees = models.PositiveIntegerField(blank=True, null=True)
    legal_status_of_firm = models.CharField(max_length=200, blank=True, null=True, choices=CATEGORY)
    catalogue = models.FileField(upload_to="files/seller_catalogues", blank=True, null=True)
    branded_video = EmbedVideoField(null=True)
<<<<<<< HEAD
    
=======
>>>>>>> d1b97b0fb238df1f15884ed799e4ff6b9878695f
    caption = models.CharField(max_length=200, blank=True, null=True)
    logo = models.ImageField(default="images/seller_banner_images/imgseller.png", upload_to="images/seller_logos", blank=True, null=True)
    banner_image =models.ImageField(default="images/seller_banner_images/imgseller.png", upload_to="images/seller_banner_images", blank=True, null=True)
     
    def __str__(self):
        return self.user.username


def sellercompany_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = SellerCompany.objects.create(user=instance)

post_save.connect(sellercompany_receiver, sender=User)

BUSINESS_TYPE_CHOICES = (
        ('Manufacturer', 'Manufacturer'),
        ('Retailer', 'Retailer'),
        ('Distributer', 'Distributer'),
        ('Wholeseller', 'Wholeseller'),
        ('Exporter', 'Exporter'),
)

# llist = Language.objects.filter(status=True)
# list1 = []
# for rs in llist:
#     list1.append((rs.code,rs.name))
# langlist = (list1)


account = Account.objects.all()
list1 = []
# for a in account:
    # list1.append((a.slug, a.slug))
SELLER_LIST = (list1)
print("Dilip", SELLER_LIST)
for i in SELLER_LIST:
    print(i[1])
class ShareDetail(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="shareuser")
    seller = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="shareseller")
    name = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(max_length=100)
    mobile = models.IntegerField()
    business_type = models.CharField(max_length=20, choices=BUSINESS_TYPE_CHOICES)
    message = models.TextField()
    send_copy = models.BooleanField(default=False)
    approve = models.BooleanField(default=False)
    send_to = models.CharField(max_length=50, choices=SELLER_LIST, blank=True, null=True)
    
    def __str__(self):
        return str(self.name) 
  
class Color(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    button = models.CharField(max_length=20,default="")
    background = models.CharField(max_length=20,default="#f5f5f5;")

    def __str__(self):
        return self.user.username

templates/dashboard/seller/bank_details.html
{% extends 'dashboard/seller/seller_base.html' %}
{% load static %}
   {% block content %}
   <!-- Showing the Error message in red while validating form -->
        <style>
            .error{
            color:red;
            font-style:italic;
                    }
                    .bmd-form-group label {
                        color: red;
                        }

 
.card [class*="card-header-"]:not(.card-header-icon):not(.card-header-text):not(.card-header-image) {
    border-radius: 3px;
    margin-top: -20px;
    padding: 11px;
    width: 184px;
}

        </style>
        <!---->
        <div class="main-panel">
            <div class="content">
                <div class="container-fluid" style="margin-top:-90px">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <h4 class="card-title">Bank Details</h4>
                                    {% comment %} <p class="card-category">Complete your Statutory Details</p> {% endcomment %}
                                </div>
                                <div class="card-body">
                                        <form action="." method="post" id="Bank_detail">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating" for id="id_bank_name">Bank Name</label>
                                                    <input type="text" class="form-control" name="bank_name"id="id_bank_name" value="{{ seller_bank.bank_name }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating" for id="id_account_no">Bank Account No.</label>
                                                    <input type="text" class="form-control" name="account_no"id="id_account_no" value="{{ seller_bank.account_no }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_bank_account_name">Bank According Your Name</label>
                                                    <input type="text" class="form-control" name="bank_account_name"id="id_bank_account_name" value="{{ seller_bank.bank_account_name}}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_ifsc_code">Bank IFSC Code</label>
                                                    <input type="text" class="form-control" name="ifsc_code"id="id_ifsc_code" value="{{ seller_bank.ifsc_code }}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_account_type">Account Type</label>
                                                    <input type="text" class="form-control" name="account_type"id="id_account_type" value="{{ seller_bank.account_type }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_name">Alernative Bank Name</label>
                                                    <input type="text" class="form-control" name="alternative_bank_name"id="id_alternative_bank_name" value="{{ seller_bank.alternative_bank_name }}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_account_no">Alernative Bank Account No.</label>
                                                    <input type="text" class="form-control" name="alternative_account_no"id="id_alternative_account_no" value="{{ seller_bank.alternative_account_no }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_account_name">Alernative Bank According Your Name</label>
                                                    <input type="text" class="form-control" name="alternative_bank_account_name"id="id_alternative_bank_account_name" value="{{ seller_bank.alternative_bank_account_name }}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_ifsc_code">Alernative Bank IFSC Code</label>
                                                    <input type="text" class="form-control" name="alternative_bank_ifsc_code"id="id_alternative_bank_ifsc_code" value="{{ seller_bank.alternative_bank_ifsc_code }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_account_type">Alernative Account Type</label>
                                                    <input type="text" class="form-control" name="alternative_bank_account_type"id="id_alternative_bank_account_type" value="{{ seller_bank.alternative_bank_account_type }}">
                                                </div>
                                            </div>
                                        </div>
                                        <input type="submit" class="btn btn-primary pull-right" value="save" style="margin-bottom:80px;">
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        {% endblock content %}
          


          

templates/dashboard/seller/myenquiry_detail.html
{% extends 'dashboard/seller/seller_base.html' %}
{% load static %}
   {% block content %}
   
<style>
.card [class*="card-header-"]:not(.card-header-icon):not(.card-header-text):not(.card-header-image) {
    border-radius: 3px;
    margin-top: -20px;
    padding: 11px;
    width: 204px;
}
</style>

    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid" style="margin-top:-78px;">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title" style="font-size: 20px;">Customer Enquiries</h4>
                  {% comment %} <p class="card-category">See Customer Enquiries</p> {% endcomment %}
                </div>
                <div class="card-body">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Mobile</th>
                        <th scope="col">Business Type</th>
                        <th scope="col">Message</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">1</th>
                        <td>{{ object.name}}</td>
                        <td>{{ object.mobile}}</td>
                        <td>{{ object.business_type}}</td>
                        <td>{{ object.message}}</td>
                      </tr>
                    </tbody>
                  </table>
                  <a href="{% url 'dashboard:seller_my_enquiry_list' %}" class="btn btn-primary pull-right">back</a>
                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

templates/dashboard/seller/seo.html
{% extends 'dashboard/seller/seller_base.html' %}
{% load static %}
{% block content %}
<!-- Showing the Error message in red while validating form -->
<style>
    .error{
    color:red;
    font-style:italic;
            }
            .bmd-form-group label {
                color: red;
                }

.card [class*="card-header-"]:not(.card-header-icon):not(.card-header-text):not(.card-header-image) {
border-radius: 3px;
margin-top: -20px;
padding: 11px;
width: 184px;
}
@media only screen and (max-width: 1200px) and (min-width: 480px) {
    #pad{
        margin-top: -400px !important;
    }

}
@media only screen and (max-width: 769px) and (min-width: 480px) {
    #pad{
        margin-top: -200px !important;
    }

}
@media only screen and (max-width: 480px) {
    #pad{
        margin-top: -250px !important;
    }

}


</style>
<!---->
<div class="main-panel">
    <div class="content">
        <div class="container-fluid" style="margin-top:-90px">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title" style="font-size: 20px;">SEO Details</h4>
                            {% comment %} <p class="card-category">Complete your Statutory Details</p> {% endcomment %}
                        </div>
                        <div class="card-body">
                            <form action = "{% url 'accounts:search_engine' %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating" for id="id_gst_no">Meta Title</label>
                                            {{ form.meta_title }}
                                        </div>
                                    </div> 
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating" for id="id_pan_no">Meta Description</label>
                                            {{ form.meta_decscription }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating" for id="id_tan_no">Meta Keywords</label>
                                            {{ form.meta_keywords }}
                                        </div>
                                    </div>
                                </div>
                                
                                <input type="submit" class="btn btn-primary pull-right"value="Save" style="margin-bottom:80px;">
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- <center>{{form.as_p}}</center> -->
{% endblock content %}