adminb2b/urls.py
from django.urls import path
from . import views
app_name="adminb2b"
urlpatterns = [
    path("", views.Adminb2bView.as_view(), name="admin_dahboard"),
    path("seller-list/", views.AdminSellerListView.as_view(), name="admin_seller_list"),
    path("seller/<int:pk>/", views.AdminSellerDetailView.as_view(), name="admin_seller_detail"),
    path("buyer-list/", views.AdminBuyerListView.as_view(), name="admin_buyer_list"),
    
    path("enquiry-list/", views.EnquiryListView.as_view(), name="enquiry_list"),
    path("enquiry-detail/<int:pk>/", views.EnquiryDetailView.as_view(), name="enquiry_detail"),

    path("enquiry-approve/<int:pk>/", views.EnquiryApproveView.as_view(), name="enquiry_approve"),
    path("enquiry-unapprove/<int:pk>/", views.EnquiryUnApproveView.as_view(), name="enquiry_unapprove"),

    path("seller-address-list/", views.SellerAddressListView.as_view(), name="seller_address_list"),
    path("seller-address-approve/<int:pk>/", views.AddressApproveView.as_view(), name="seller_address_approve"),
    path("seller-address-unapprove/<int:pk>/", views.AddressUnApproveView.as_view(), name="seller_address_unapprove"),
    path("seller-address-admin-account-approve-unapprove-notification/admin-user-account-view/", views.admin_account_view),

    path("admin-user-list/", views.AdminUserListView.as_view(), name="admin_user_list"),
    path("admin-user-activate/<int:pk>/", views.UserActivateView.as_view(), name="admin_user_activate"),
    path("admin-user-deactivate/<int:pk>/", views.UserDeactivateveView.as_view(), name="admin_user_deactivate"),

]

b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from product.models import Order
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),
    path('editor-choice/', TemplateView.as_view(template_name="company/choice.html"), name="choice"),
    path('category-leader/', TemplateView.as_view(template_name="company/leader.html"), name="leader"),
    path('fund-your-order-center/', TemplateView.as_view(template_name="company/order-center.html"), name="center"),
    path('customer-with-viswas-certification/', TemplateView.as_view(template_name="company/certification.html"), name="certification"),

    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('adminb2b/', include('adminb2b.urls', namespace="adminb2b")),
    path('subscription/', include('subscription.urls', namespace="subscription")),

    path('', include("product.urls", namespace="product")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),

    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),


    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryListView.as_view(), name="seller_my_enquiry_list"),
    path('seller/my-enquiry/<int:pk>/',views.SellerMyEnquiryDetailView.as_view(), name="seller_my_enquiry_detail"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('<str:slug>/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),
    path('seller/banner-logo/<str:slug>/',views.SellerBannerLogoView.as_view(), name="seller_banner_logo"),
    path('seller/color/<str:slug>/',views.ColorView.as_view(), name="seller_color"),

    path('seller/create-product/',views.ProductCreateView.as_view(), name="create_product"),
    path('seller/update-product/<int:pk>/',views.ProductUpdateView.as_view(), name="update_product"),
    path('seller/create-bulk-product/',views.BulkProductUploadView.as_view(), name="create_bulk_product"),

    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    # path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),
    path('buyer-share/',views.SellerShareView.as_view(), name="seller_share"),
    path('buyer-seller-dashboard-product-variant-upload-record-list/',views.dashboard_account_view),
    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),

    path('share-detail-admin/',views.ShareDetailAdmin.as_view(), name="share_detail_admin"),

    path('seller-order-list/', views.SellerOrderListView.as_view(), name='seller_order_list'),
    path('seller-order-detail/<int:pk>/', views.SellerOrderDetailView.as_view(), name='seller_order_detail'),
    path('generate-pdf/<int:pk>/', views.GeneratePdf.as_view(), name='generate_pdf'),

    path('seller-order-confirmed/<int:pk>/', views.SellerOrderConfirmedView.as_view(), name='seller_order_confirmed'),
    path('seller-order-processing/<int:pk>/', views.SellerOrderProcessingView.as_view(), name='seller_order_processing'),
    path('seller-quality-check/<int:pk>/', views.SellerQualityCheckView.as_view(), name='seller_quality_check'),
    path('seller-product-disparch/<int:pk>/', views.SellerProductDispatchView.as_view(), name='seller_product_dispatch'),
    path('seller-product-selivered/<int:pk>/', views.SellerProducrDeliveredView.as_view(), name='seller_product_delivered'),



    path('add-to-cart/<str:slug>/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<str:slug>/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove-product-from-cart/<str:slug>/<int:pk>/', views.remove_single_product_from_cart, name='remove_single_product_from_cart'),
    path('<str:slug>/cart/', views.CartView.as_view(), name='cart'),


    path('generate-otp/', views.GenerateOtpView.as_view(), name='generate_otp'),
    path('verify-otp/', views.VerifyOtpView.as_view(), name='verify_otp'),

    path('buyer-enquiry/', views.BuyerEnquiryView.as_view(), name='buyer_enquiry'),

    path('credit-terms/', views.credit_terms_view, name='credit_terms'),
    
    path('seller-paid-service/', views.seller_paid_service, name='seller_paid_service'),

]

product/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name="product"

urlpatterns = [
    path("handlerequest/", views.handlerequest, name="HandleRequest"),
    path("back/", views.back, name="back"),
    path("preview/<str:slug>/",views.SitePreviewView.as_view(), name="preview"),


    path("",views.HomeView, name="home_list"),
    path("category/",views.category, name="category"),
    path("<str:slug>/",views.WebsiteHomeList.as_view(), name="website_home_list"),

    path("product/checkout/",views.CheckoutView.as_view(), name="product_checkout"),
    path("product/order-track/<int:pk>/",views.ProductTrackView.as_view(), name="product_order_track"),

    path("product/add-to-cart/<str:slug>/<int:pk>/",views.AddToCart.as_view(), name="add_to_cart"),
    
    path("product/cart-summary/",views.CartView.as_view(), name="cart_summary"),

    path("product/remove-from-cart/<int:pk>/",views.RemoveFromCartView.as_view(), name="remove_from_cart"),
    path("product/remove-single-item-from-cart/<int:pk>/",views.RemoveSingleItemFromCartView.as_view(), name="remove_single_item_from_cart"),
    path("product/add-single-item-to-cart/<int:pk>/",views.AddSingleItemToCartView.as_view(), name="add_single_item_to_cart"),
    ####compare route########

    path("product/compare-product-list/",views.CompareView.as_view(), name="compare_view"),

    path("product/remove-compare-product/<int:pk>/",views.RemoveFromCompareView.as_view(), name="remove_from_compare"),
    # path("product/remove-single-item-compare-product/<int:pk>/",views.RemoveSingleItemFromCompareView.as_view(), name="remove_single_item_from_compare"),
    path("product/add-single-item-to-compare-product/<int:pk>/",views.AddSingleItemToCompareView.as_view(), name="add_single_item_to_compare"),

    ]

adminb2b/models.py
from django.db import models

# Create your models here.

templates/dashboard/adminb2b/analytics.html
    {% extends 'dashboard/seller/seller_base.html' %}
    {% load static %}
       {% block content %}

<style>
.card [class*="card-header-"]:not(.card-header-icon):not(.card-header-text):not(.card-header-image) {
    border-radius: 3px;
    margin-top: -20px;
    padding: 11px;
    width: 184px;
}
</style>
    <div class="main-panel">
   
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid" style="margin-top: -80px;">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Edit Profile</h4>
                  {% comment %} <p class="card-category">Complete your profile</p> {% endcomment %}
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-9">
                      <img class="img-fluid" src="{% static 'seller/assets/img/calender.jpg' %}" alt="">
                    </div>
                    <div class="col-md-3">
                      <img class="img-fluid" src="{% static 'seller/assets/img/manufacture-dashbord-edited-copy.jpg' %}" alt="">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-7 mt-3">
                      <img class="img-fluid" src="{% static 'seller/assets/img/sales-to-date.png'%}" alt="">
                      <img class="img-fluid" src="{% static 'seller/assets/img/product-performance.png '%}" alt="">
                    </div>
                    <div class="col-md-5 mt-3">
                      <img class="img-fluid" src="{% static 'seller/assets/img/sales-by-region.png" '%}"alt="">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 mt-3">
                      <img class="img-fluid w-100" src="{% static 'seller/assets/img/Recent-Tickets.jpg' %}" alt="">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

templates/dashboard/adminb2b/buyer_detail.html
{% extends 'dashboard/adminb2b/adminb2b_base.html' %}
{% load static %}
{% block content %}
<div class="main-panel">
    <div class="content">
        <div class="container-fluid" >
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">Buyer Details</h4>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered border-info">
                                <thead>    
                                  <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">name</th>
                                    <th scope="col">mobile</th>
                                    <th scope="col">product</th>
                                    <th scope="col">ordered on</th>
                                    <th scope="col">ordered from</th>
                                    <th scope="col">Payment</th>
                                    <th scope="col">status</th>
                                </tr>
                                </thead>
                                <tbody>
                                   
                                  <tr>
                                    <th scope="row">1</th>
                                    <td>{{ object.user.username }}</td>
                                    <td>{{ object.user.account.mobile }}</td>
                                    <td>
                                        {% for x in object.products.all %}
                                        {{ x.product }}<br>
                                        <img src="{{ x.product.image1.url }}"class="rounded-circle" alt="Product image" height=50px;><hr class="py-2 bg-info"> 
                                        {% endfor %}
                                    </td>
                                    <td>{{ object.ordered_date }}</td>
                                    <td>{{ object.user.ordershipping_address.city }}</td>
                                    <td>{{ object.payment.txn_amount }}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                {{ object.status }}
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                              <a class="dropdown-item" href="{% url 'dashboard:seller_ordered' object.pk %}">ordered</a>
                                              <a class="dropdown-item" href="{% url 'dashboard:seller_packing' object.pk %}">packing</a>
                                              <a class="dropdown-item" href="{% url 'dashboard:seller_shipping' object.pk %}">shipping</a>
                                              <a class="dropdown-item" href="{% url 'dashboard:seller_delivered' object.pk %}">delivered</a>
                                              <a class="dropdown-item" href="{% url 'dashboard:seller_cancelled' object.pk %}">shipping</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'dashboard:seller_order_list' %}" class="btn btn-primary pull-right">go back</a>

                            
                            {% for i in object.products_set.all %}
                                {{i.name}}
                            {% endfor %}
                                
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/dashboard/adminb2b/history.html
{% extends 'dashboard/seller/seller_base.html' %}
{% load static %}
   {% block content %}
 <style>
    .card [class*="card-header-"]:not(.card-header-icon):not(.card-header-text):not(.card-header-image) {
        border-radius: 3px;
        margin-top: -20px;
        padding: 11px;
        width: 300px;
    }
    </style>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid" >
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid" style="margin-top: -78px;">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Today - Tuesday, xx/xx/xxxx</h4>
                  <!-- <p class="card-category">Complete your profile</p> -->
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <tr>
                          <th>
                            <span class="form-check d-inline-block">
                              <label class="form-check-label">
                                  <input class="form-check-input" type="checkbox" value="">
                                  <span class="form-check-sign">
                                    <span class="check"></span>
                                  </span>
                              </label>
                            </span>
                            time
                          </th>
                          <th class="w-75">
                            Activity
                          </th>
                          <th>
                            Action
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            <span class="form-check d-inline-block">
                              <label class="form-check-label">
                                  <input class="form-check-input" type="checkbox" value="">
                                  <span class="form-check-sign">
                                    <span class="check"></span>
                                  </span>
                              </label>
                            </span>
                            12:30 Pm
                          </td>
                          <td>
                            Lorem
                          </td>
                          <td>
                            <i class="material-icons text-danger">delete</i>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

templates/dashboard/adminb2b/rearrange_product.html
{% extends 'dashboard/adminb2b/adminb2b_base.html' %}
{% load static %}
   {% block content %}
<style>
.card [class*="card-header-"]:not(.card-header-icon):not(.card-header-text):not(.card-header-image) {
    border-radius: 3px;
    margin-top: -20px;
    padding: 11px;
    width: 204px;
}


</style>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            </button>
                    <div class="collapse navbar-collapse justify-content-end">
                        <form class="navbar-form">
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                    <i class="material-icons">search</i>
                <div class="ripple-container"></div>
            </button>
                            </div>
                        </form>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid" style="margin-top: -42px;">
                    <div class="row">
                        <div class="col-md-12" style="margin-top: -34px">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <h4 class="card-title">Rearrange Product</h4>
                                </div>
                                <div class="card-body">

                                    <table class="table table-bordered">
                                        <thead>
                                          <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Seller Name</th>
                                            <th scope="col">Product Name</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Brand</th>
                                            <th scope="col">Color</th>
                                            <th scope="col">Warranty</th>
                                            <th scope="col">Add To Site</th>
                                            <th scope="col">Add to Home</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in object_list %}                                              
                                          <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td><a href="{% url 'product:website_home_list' i.user.account.slug %}">{{ i.user.account.company_name }}</a></td>
                                            <td>{{ i.name }}</td>
                                            <td>{{ i.price }}</td>
                                            <td>{{ i.brand }}</td>
                                            <td>{{ i.color }}</td>
                                            <td>{{ i.warranty }}</td>
                                            <td>{% if i.arrange %}<a href="{% url 'dashboard:seller_unarrange_product' i.id %}">{{ i.arrange }}</a>{% else %}<a href="{% url 'dashboard:seller_arrange_product' i.id %}">{{ i.arrange }}</a>{% endif %}</td>
                                            <td>{% if i.add_home %}<a href="{% url 'dashboard:seller_remove_home_product' i.id %}">{{ i.add_home }}</a>{% else %}<a href="{% url 'dashboard:seller_add_home_product' i.id %}">{{ i.add_home }}</a>{% endif %}</td>
                                          </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock content %}
          

templates/dashboard/adminb2b/seller_list.html
{% extends 'dashboard/adminb2b/adminb2b_base.html' %}
{% load static %}
{% block content %}
<div class="main-panel">
    <div class="content">
        <div class="container-fluid" >
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">Seller Lists</h4>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered border-info">
                                <thead>    
                                  <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">First Name</th>
                                    <th scope="col">Last Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Mobile</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for obj in seller_list %}
                                  <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td><a href="{% url 'product:website_home_list' obj.user.account.slug %}">{{ obj.user.first_name }}</a></td>
                                    <td>{{ obj.user.last_name }}</td>
                                    <td>
                                        {{ obj.user.email }}
                                    </td>
                                    <td>{{ obj.user.account.mobile }}</td>
                                </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}