accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path("redirect/", views.login_redirect_view, name="redirect"),
    path("account-profile/", views.BuyerProfileView.as_view(), name="buyer_profile"),
    path("account-profile-details-with-foreignkey-relationship/account/detail/",views.account_view),
    
    path("search-engine/", views.SearchEngineView.as_view(), name="search_engine")
]

b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from product.models import Order
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),
    path('editor-choice/', TemplateView.as_view(template_name="company/choice.html"), name="choice"),
    path('category-leader/', TemplateView.as_view(template_name="company/leader.html"), name="leader"),
    path('fund-your-order-center/', TemplateView.as_view(template_name="company/order-center.html"), name="center"),
    path('customer-with-viswas-certification/', TemplateView.as_view(template_name="company/certification.html"), name="certification"),

    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('adminb2b/', include('adminb2b.urls', namespace="adminb2b")),
    path('subscription/', include('subscription.urls', namespace="subscription")),

    path('', include("product.urls", namespace="product")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),

    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),


    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryListView.as_view(), name="seller_my_enquiry_list"),
    path('seller/my-enquiry/<int:pk>/',views.SellerMyEnquiryDetailView.as_view(), name="seller_my_enquiry_detail"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('<str:slug>/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),
    path('seller/banner-logo/<str:slug>/',views.SellerBannerLogoView.as_view(), name="seller_banner_logo"),
    path('seller/color/<str:slug>/',views.ColorView.as_view(), name="seller_color"),

    path('seller/create-product/',views.ProductCreateView.as_view(), name="create_product"),
    path('seller/update-product/<int:pk>/',views.ProductUpdateView.as_view(), name="update_product"),
    path('seller/create-bulk-product/',views.BulkProductUploadView.as_view(), name="create_bulk_product"),

    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    # path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),
    path('buyer-share/',views.SellerShareView.as_view(), name="seller_share"),
    path('buyer-seller-dashboard-product-variant-upload-record-list/',views.dashboard_account_view),
    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),

    path('share-detail-admin/',views.ShareDetailAdmin.as_view(), name="share_detail_admin"),

    path('seller-order-list/', views.SellerOrderListView.as_view(), name='seller_order_list'),
    path('seller-order-detail/<int:pk>/', views.SellerOrderDetailView.as_view(), name='seller_order_detail'),
    path('generate-pdf/<int:pk>/', views.GeneratePdf.as_view(), name='generate_pdf'),

    path('seller-order-confirmed/<int:pk>/', views.SellerOrderConfirmedView.as_view(), name='seller_order_confirmed'),
    path('seller-order-processing/<int:pk>/', views.SellerOrderProcessingView.as_view(), name='seller_order_processing'),
    path('seller-quality-check/<int:pk>/', views.SellerQualityCheckView.as_view(), name='seller_quality_check'),
    path('seller-product-disparch/<int:pk>/', views.SellerProductDispatchView.as_view(), name='seller_product_dispatch'),
    path('seller-product-selivered/<int:pk>/', views.SellerProducrDeliveredView.as_view(), name='seller_product_delivered'),



    path('add-to-cart/<str:slug>/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<str:slug>/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove-product-from-cart/<str:slug>/<int:pk>/', views.remove_single_product_from_cart, name='remove_single_product_from_cart'),
    path('<str:slug>/cart/', views.CartView.as_view(), name='cart'),


    path('generate-otp/', views.GenerateOtpView.as_view(), name='generate_otp'),
    path('verify-otp/', views.VerifyOtpView.as_view(), name='verify_otp'),

    path('buyer-enquiry/', views.BuyerEnquiryView.as_view(), name='buyer_enquiry'),

    path('credit-terms/', views.credit_terms_view, name='credit_terms'),
    
    path('seller-paid-service/', views.seller_paid_service, name='seller_paid_service'),

]

product/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name="product"

urlpatterns = [
    path("handlerequest/", views.handlerequest, name="HandleRequest"),
    path("back/", views.back, name="back"),
    path("preview/<str:slug>/",views.SitePreviewView.as_view(), name="preview"),


    path("",views.HomeView, name="home_list"),
    path("category/",views.category, name="category"),
    path("<str:slug>/",views.WebsiteHomeList.as_view(), name="website_home_list"),

    path("product/checkout/",views.CheckoutView.as_view(), name="product_checkout"),
    path("product/order-track/<int:pk>/",views.ProductTrackView.as_view(), name="product_order_track"),

    path("product/add-to-cart/<str:slug>/<int:pk>/",views.AddToCart.as_view(), name="add_to_cart"),
    
    path("product/cart-summary/",views.CartView.as_view(), name="cart_summary"),

    path("product/remove-from-cart/<int:pk>/",views.RemoveFromCartView.as_view(), name="remove_from_cart"),
    path("product/remove-single-item-from-cart/<int:pk>/",views.RemoveSingleItemFromCartView.as_view(), name="remove_single_item_from_cart"),
    path("product/add-single-item-to-cart/<int:pk>/",views.AddSingleItemToCartView.as_view(), name="add_single_item_to_cart"),
    ####compare route########

    path("product/compare-product-list/",views.CompareView.as_view(), name="compare_view"),

    path("product/remove-compare-product/<int:pk>/",views.RemoveFromCompareView.as_view(), name="remove_from_compare"),
    # path("product/remove-single-item-compare-product/<int:pk>/",views.RemoveSingleItemFromCompareView.as_view(), name="remove_single_item_from_compare"),
    path("product/add-single-item-to-compare-product/<int:pk>/",views.AddSingleItemToCompareView.as_view(), name="add_single_item_to_compare"),

    ]

templates/dashboard/buyer/buyer_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'buyer/assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'buyer/assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Dashboard
  </title>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'buyer/assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'buyer/assets/demo/demo.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="{% static 'buyer/assets/img/sidebar-1.jpg' %}">
      <div class="logo position-relative">
        <a href="#" class="simple-text logo-normal">
          Company Logo
        </a>
      </div>
      <div class="sidebar-wrapper position-relative">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          {% if request.path == "/accounts/account-profile/" %}
          <li class="nav-item active">
            {% else %}
            <li class="nav-item">
              {% endif %}
            <a class="nav-link" href="{% url 'accounts:buyer_profile' %}">
              <i class="material-icons">account_circle</i>
              <p>My Account</p>
            </a>
          </li>
          {% if request.path == "/dashboard/buyer-order/" %}
          <li class="nav-item active">
            {% else %}
            <li class="nav-item">
              {% endif %}
            <a class="nav-link" href="{% url 'dashboard:buyer_order' %}">
              <i class="material-icons">star_border</i>
              <p>My Order</p>
            </a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_message' %}">
              <i class="material-icons">message</i>
              <p>Message</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_offer_request_detail' %}">
              <i class="material-icons">local_offer</i>
              <p> Offer Request Details</p>
            </a>
          </li> -->
          {% if request.path == "/dashboard/buyer-enquiry/" %}
          <li class="nav-item active">
            {% else %}
            <li class="nav-item">
              {% endif %}
            <a class="nav-link" href="{% url 'dashboard:buyer_enquiry' %}">
              <i class="material-icons">grading</i>
              <p>My Enquiries</p>
            </a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="material-icons">local_activity</i>
              <p>My Recent Activity</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="material-icons">favorite</i>
              <p>My Favourite</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_downloads' %}">
              <i class="material-icons">cloud_download</i>
              <p>My Download</p>
            </a>
          </li> -->
          {% if request.path == "/dashboard/buyer-share/" %}
          <li class="nav-item active">
            {% else %}
            <li class="nav-item">
              {% endif %}
            <a class="nav-link" href="{% url 'dashboard:buyer_share' %}">
              <i class="material-icons">share</i>
              <p>Share and Earn</p>
            </a>
          </li>
          <li class="nav-item home">
            <a class="nav-link" href="{% url 'product:home_list' %}">
              <i class="material-icons">home</i>
              <p>Home</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-8 offset-3">
      {% if messages %}
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              {% endfor %}
      {% endif %}
    </div>
    {% block content %}
        
    {% endblock content %}
        
  </div>
  
  <!--   Core JS Files   -->
  <script src="{% static 'buyer/assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'buyer/assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'buyer/assets/js/core/bootstrap-material-design.min.js' %}"></script>
  <script src="{% static 'buyer/assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Plugin for the momentJs  -->
  <script src="{% static 'buyer/assets/js/plugins/moment.min.js' %}"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{% static 'buyer/assets/js/plugins/sweetalert2.js' %}"></script>
  <!-- Forms Validations Plugin -->
  <script src="{% static 'buyer/assets/js/plugins/jquery.validate.min.js' %}"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{% static 'buyer/assets/js/plugins/jquery.bootstrap-wizard.js' %}"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-selectpicker.js' %}"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="{% static 'buyer/assets/js/plugins/jquery.dataTables.min.js' %}"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-tagsinput.js' %}"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{% static 'buyer/assets/js/plugins/jasny-bootstrap.min.js' %}"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{% static 'buyer/assets/js/plugins/fullcalendar.min.js' %}"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{% static 'buyer/assets/js/plugins/jquery-jvectormap.js' %}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'buyer/assets/js/plugins/nouislider.min.js' %}"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js' %}"></script>
  <!-- Library for adding dinamically elements -->
  <script src="{% static 'buyer/assets/js/plugins/arrive.min.js' %}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="{% static 'buyer/assets/js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'buyer/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'buyer/assets/demo/demo.js' %}"></script>
  
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>
</body>

</html>

templates/dashboard/buyer/order.html
{% extends 'dashboard/buyer/buyer_base.html' %}
{% load static %}
{% block content %}
  
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" href="javascript:;">My Order</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
                    <div class="collapse navbar-collapse justify-content-end">
                        <form class="navbar-form">
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:;">
                                    <i class="material-icons">dashboard</i>
                                    <p class="d-lg-none d-md-block">
                                        Stats
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">notifications</i>
                                    <!-- <span class="notification">5</span> -->
                                    <p class="d-lg-none d-md-block">
                                        Some Actions
                                    </p>
                                </a>
                                <!-- <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Mike John responded to your email</a>
                                    <a class="dropdown-item" href="#">You have 5 new tasks</a>
                                    <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                                    <a class="dropdown-item" href="#">Another Notification</a>
                                    <a class="dropdown-item" href="#">Another One</a>
                                </div> -->
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">person</i>
                                    <p class="d-lg-none d-md-block">
                                        Account
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                                    <a class="dropdown-item" href="{% url 'accounts:buyer_profile' %}">Profile</a>
                                    <!-- <a class="dropdown-item" href="#">Settings</a> -->
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <h4 class="card-title">My Order Details</h4>
                                </div>
                                <div class="card-body">
                                    <!-- <form>
                                        <div class="row">
                                            <div class="col-md-6 offset-3">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Enter your Query</label>
                                                    <input type="text" class="form-control">
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Search</button>
                                        </div>
                                    </form> -->
                                    <div class="table-responsive table-bordered mt-4">
                                        <table class="table">
                                          <thead class=" text-primary">
                                            <tr>
                                              <th>#</th>
                                              {% comment %} <th>Invoice No.</th> {% endcomment %}
                                              <th>product name</th>
                                              <th>product color</th>
                                              <th>quantity</th>
                                              <th>price</th>
                                              <th>Seller Name</th>
                                              <th>Seller address</th>
                                              <th>Status</th>
                                              <!-- <th> Action</th> -->
                                            </tr>
                                          </thead>
                                          <tbody>
                                            {% for ord in order %}
                                            <tr>
                                              <td>{{forloop.counter}} </td>
                                              {% comment %} <td>{{ord.id}} </td> {% endcomment %}
                                              <td>{{ ord.product.name }}</td>
                                              <td class="text-center"><div style="width:30px; height:30px; border-color: coral;border-style: solid;border-radius: 25px; background-color:{{ ord.color }}"></div></td>
                                              <td>{{ ord.quantity }}</td>
                                              <td>{{ ord.amount }}/-</td>
                                              <td><a href="{% url 'product:website_home_list' ord.user.account.slug %}">{{ ord.user.account.company_name }}</a></td>
                                              <td>{{ ord.seller.account.state }}, {{ ord.seller.account.pincode }} </td>
                                              <td><a href="{% url 'product:product_order_track' ord.pk %}">{{ord.status }}</a></td>
                                            </tr>
                                            {% endfor %}
                                          </tbody>
                                        </table>
                                      </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}